project_id = "rthnnahjmvlkmpefvbxm"

[functions.convert-to-lineart]
verify_jwt = false

[functions.guest-order]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.shopify-order-webhook]
verify_jwt = false

[functions.send-review-requests]
verify_jwt = false

[functions.affiliate-signup]
verify_jwt = false
